name: Sonar_Deploy

on:
  pull_request:
    branches:
      - main
    
  push:
    branches:
      - develop
      
jobs:
  Display_Data:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort